# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import shutil
import pickle
from Main import Organizer, Game


m = Organizer()

class Ui_MainWindow(object):
    def populate_list(self):
        self.list_game.clear()
        self.games = m.get_games()
        for item in self.games:
            self.list_game.addItem(item)
    
    def add_ds3(self):
        # m.add_game("DS3", str(QtWidgets.QFileDialog.getOpenFileName()[0].replace("/", "\\")))
        a = str(QtWidgets.QFileDialog.getOpenFileName()[0])
        print(a)
        # self.populate_list()

    def remove_game(self):
        todel = self.list_game.currentItem().text()
        m.remove_game(todel)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(505, 365)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list_game = QtWidgets.QListWidget(self.centralwidget)
        self.list_game.setGeometry(QtCore.QRect(20, 40, 351, 271))
        self.list_game.setObjectName("list_game")
        self.label_game = QtWidgets.QLabel(self.centralwidget)
        self.label_game.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.label_game.setObjectName("label_game")
        self.button_add = QtWidgets.QPushButton(self.centralwidget)
        self.button_add.setGeometry(QtCore.QRect(380, 40, 111, 23))
        self.button_add.setObjectName("button_add")
        self.button_add.clicked.connect(self.add_ds3)
        self.button_remove = QtWidgets.QPushButton(self.centralwidget)
        self.button_remove.setGeometry(QtCore.QRect(380, 70, 111, 23))
        self.button_remove.setObjectName("button_remove")
        self.button_remove.clicked.connect(self.remove_game)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 505, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_game.setText(_translate("MainWindow", "Games:"))
        self.button_add.setText(_translate("MainWindow", "Add"))
        self.button_remove.setText(_translate("MainWindow", "Remove"))
        self.populate_list()

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())

print(m.Game_dict)