# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    games = ["DS1", "DS2", "DS3"]

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(678, 583)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dropdown_game = QtWidgets.QComboBox(self.centralwidget)
        self.dropdown_game.setGeometry(QtCore.QRect(20, 70, 251, 22))
        self.dropdown_game.setMouseTracking(False)
        self.dropdown_game.setObjectName("dropdown_game")
        self.dropdown_game.addItem("")
        self.dropdown_game.addItem("")
        self.dropdown_game.addItem("")
        self.label_game = QtWidgets.QLabel(self.centralwidget)
        self.label_game.setGeometry(QtCore.QRect(20, 40, 111, 20))
        self.label_game.setObjectName("label_game")
        self.dropdown_profile = QtWidgets.QComboBox(self.centralwidget)
        self.dropdown_profile.setGeometry(QtCore.QRect(280, 70, 281, 22))
        self.dropdown_profile.setObjectName("dropdown_profile")
        self.dropdown_profile.addItem("")
        self.dropdown_profile.addItem("")
        self.dropdown_profile.addItem("")
        self.label_profile = QtWidgets.QLabel(self.centralwidget)
        self.label_profile.setGeometry(QtCore.QRect(280, 40, 111, 20))
        self.label_profile.setObjectName("label_profile")
        self.buton_profile = QtWidgets.QPushButton(self.centralwidget)
        self.buton_profile.setGeometry(QtCore.QRect(570, 70, 75, 23))
        self.buton_profile.setObjectName("buton_profile")
        self.Section_view = QtWidgets.QListWidget(self.centralwidget)
        self.Section_view.setGeometry(QtCore.QRect(20, 140, 631, 331))
        self.Section_view.setObjectName("Section_view")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 490, 291, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 490, 291, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 678, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def add_items(self):
        for item in Ui_MainWindow.games:
            self.Section_view.addItem(item)
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dropdown_game.setItemText(0, _translate("MainWindow", "Game1"))
        self.dropdown_game.setItemText(1, _translate("MainWindow", "Game2"))
        self.dropdown_game.setItemText(2, _translate("MainWindow", "Game3"))
        self.label_game.setText(_translate("MainWindow", "Game:"))
        self.dropdown_profile.setItemText(0, _translate("MainWindow", "Profile1"))
        self.dropdown_profile.setItemText(1, _translate("MainWindow", "Profile2"))
        self.dropdown_profile.setItemText(2, _translate("MainWindow", "Profile3"))
        self.label_profile.setText(_translate("MainWindow", "Profile:"))
        self.buton_profile.setText(_translate("MainWindow", "Edit profiles"))
        self.pushButton.setText(_translate("MainWindow", "Import savefile"))
        self.pushButton_2.setText(_translate("MainWindow", "Load savefile"))
        self.add_items()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
