# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(678, 583)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dropdown_game = QtWidgets.QComboBox(self.centralwidget)
        self.dropdown_game.setGeometry(QtCore.QRect(20, 70, 251, 22))
        self.dropdown_game.setMouseTracking(False)
        self.dropdown_game.setObjectName("dropdown_game")
        self.dropdown_game.addItem("")
        self.dropdown_game.addItem("")
        self.dropdown_game.addItem("")
        self.label_game = QtWidgets.QLabel(self.centralwidget)
        self.label_game.setGeometry(QtCore.QRect(20, 40, 111, 20))
        self.label_game.setObjectName("label_game")
        self.dropdown_profile = QtWidgets.QComboBox(self.centralwidget)
        self.dropdown_profile.setGeometry(QtCore.QRect(280, 70, 261, 22))
        self.dropdown_profile.setObjectName("dropdown_profile")
        self.dropdown_profile.addItem("")
        self.dropdown_profile.addItem("")
        self.dropdown_profile.addItem("")
        self.label_profile = QtWidgets.QLabel(self.centralwidget)
        self.label_profile.setGeometry(QtCore.QRect(280, 40, 111, 20))
        self.label_profile.setObjectName("label_profile")
        self.button_profile = QtWidgets.QPushButton(self.centralwidget)
        self.button_profile.setGeometry(QtCore.QRect(554, 70, 91, 23))
        self.button_profile.setObjectName("button_profile")
        self.section_view = QtWidgets.QListWidget(self.centralwidget)
        self.section_view.setGeometry(QtCore.QRect(20, 140, 631, 331))
        self.section_view.setObjectName("section_view")
        self.button_import = QtWidgets.QPushButton(self.centralwidget)
        self.button_import.setGeometry(QtCore.QRect(20, 490, 291, 23))
        self.button_import.setObjectName("button_import")
        self.button_load = QtWidgets.QPushButton(self.centralwidget)
        self.button_load.setGeometry(QtCore.QRect(360, 490, 291, 23))
        self.button_load.setObjectName("button_load")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 678, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Universal Save Organizer"))
        self.dropdown_game.setItemText(0, _translate("MainWindow", "Game1"))
        self.dropdown_game.setItemText(1, _translate("MainWindow", "Game2"))
        self.dropdown_game.setItemText(2, _translate("MainWindow", "Game3"))
        self.label_game.setText(_translate("MainWindow", "Game:"))
        self.dropdown_profile.setItemText(0, _translate("MainWindow", "Profile1"))
        self.dropdown_profile.setItemText(1, _translate("MainWindow", "Profile2"))
        self.dropdown_profile.setItemText(2, _translate("MainWindow", "Profile3"))
        self.label_profile.setText(_translate("MainWindow", "Profile:"))
        self.button_profile.setText(_translate("MainWindow", "Edit profiles..."))
        self.button_import.setText(_translate("MainWindow", "Import savefile"))
        self.button_load.setText(_translate("MainWindow", "Load savefile"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
