# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profiles_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(516, 395)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.box_games = QtWidgets.QComboBox(self.centralwidget)
        self.box_games.setGeometry(QtCore.QRect(30, 40, 191, 22))
        self.box_games.setObjectName("box_games")
        self.box_games.addItem("")
        self.box_games.addItem("")
        self.box_games.addItem("")
        self.label_game = QtWidgets.QLabel(self.centralwidget)
        self.label_game.setGeometry(QtCore.QRect(30, 20, 47, 13))
        self.label_game.setObjectName("label_game")
        self.list_profiles = QtWidgets.QListWidget(self.centralwidget)
        self.list_profiles.setGeometry(QtCore.QRect(30, 100, 381, 251))
        self.list_profiles.setObjectName("list_profiles")
        self.button_new = QtWidgets.QPushButton(self.centralwidget)
        self.button_new.setGeometry(QtCore.QRect(430, 100, 75, 23))
        self.button_new.setObjectName("button_new")
        self.button_delete = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete.setGeometry(QtCore.QRect(430, 130, 75, 23))
        self.button_delete.setObjectName("button_delete")
        self.button_edit = QtWidgets.QPushButton(self.centralwidget)
        self.button_edit.setGeometry(QtCore.QRect(230, 40, 111, 23))
        self.button_edit.setObjectName("button_edit")
        self.label_profile = QtWidgets.QLabel(self.centralwidget)
        self.label_profile.setGeometry(QtCore.QRect(30, 80, 47, 13))
        self.label_profile.setObjectName("label_profile")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 516, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.box_games.setItemText(0, _translate("MainWindow", "Game 1"))
        self.box_games.setItemText(1, _translate("MainWindow", "Game 2"))
        self.box_games.setItemText(2, _translate("MainWindow", "Game 3"))
        self.label_game.setText(_translate("MainWindow", "Game:"))
        self.button_new.setText(_translate("MainWindow", "New"))
        self.button_delete.setText(_translate("MainWindow", "Delete"))
        self.button_edit.setText(_translate("MainWindow", "Edit games..."))
        self.label_profile.setText(_translate("MainWindow", "Profiles:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
